### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by stertingen** [ros-infrastructure/rosdistro#153]
```
Traceback (most recent call last):
  File "/home/hermann/src/gen-rospkg/main.py", line 28, in <module>
    xmls = dist.get_source_repo_package_xmls(repo.name)
  File "/usr/lib/python3.8/site-packages/rosdistro/distribution.py", line 95, in get_source_repo_package_xmls
    repo_cache = mp(self.repositories[repo_name].source_repository)
  File "/usr/lib/python3.8/site-packages/rosdistro/manifest_provider/github.py", line 87, in github_source_manifest_provider
    authheader = 'Basic %s' % base64.b64encode('%s:%s' % (GITHUB_USER, GITHUB_PASSWORD))
  File "/usr/lib/python3.8/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
```

**Comment by dirk-thomas** [comment]
Thank you for the report. Please see #154 for the proposed fix and it would be great if your could comment if it resolves the issue for you.

**Comment by stertingen** [comment]
> Thank you for the report. Please see #154 for the proposed fix and it would be great if your could comment if it resolves the issue for you.

Thanks for the quick response! The PR does fix the issue indeed.
