### ISSUE TITLE
add-on distribution with non-released packages breaks rosdep

### ISSUE THREAD

**Issue by mikeferguson** [ros-infrastructure/rosdistro#49]
I have a custom rosdistro with an add-on distribution file. If all repositories specified have "release" keys everything with rosdep and bloom works great. However, we have a repository we build test jobs against (and only test jobs) -- if I leave this in the distribution file, I get the following traceback on "rosdep update":

```
ERROR: Rosdep experienced an error: 'NoneType' object has no attribute 'package_names'
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.0

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 343, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 351, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 533, in command_update
    error_handler=update_error_handler)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 466, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 146, in get_gbprepo_as_rosdep_data
    distro_file = get_release_file(gbpdistro)
  File "/usr/lib/python2.7/dist-packages/rosdep2/rosdistrohelper.py", line 76, in get_release_file
    dist_file = rosdistro.get_distribution_file(get_index(), distro)
  File "/usr/lib/python2.7/dist-packages/rosdistro/__init__.py", line 129, in get_distribution_file
    return create_distribution_file(dist_name, data)
  File "/usr/lib/python2.7/dist-packages/rosdistro/distribution_file.py", line 135, in create_distribution_file
    combined_dist_file.merge(dist_file)
  File "/usr/lib/python2.7/dist-packages/rosdistro/distribution_file.py", line 100, in merge
    for pkg_name in other_repo.release_repository.package_names:
AttributeError: 'NoneType' object has no attribute 'package_names'
```

**Comment by dirk-thomas** [comment]
Am I understanding it correctly that you have a release entry which contains no package names?

If yes, what is the purpose of that?

If no, can you please post an example snippet to clarify your exact information in the distribution file?

**Comment by dirk-thomas** [comment]
Released as 0.4.2.

**Comment by dirk-thomas** [comment]
Thank you for the report!

**Comment by mikeferguson** [comment]
And thanks for the quick fix!
